<?php
$curl_errno = array(
		7  => "CURLE_COULDNT_CONNECT",
		8  => "CURLE_FTP_WEIRD_SERVER_REPLY",
		9  => "CURLE_FTP_ACCESS_DENIED",
		10 => "CURLE_FTP_USER_PASSWORD_INCORRECT",
		11 => "CURLE_FTP_WEIRD_PASS_REPLY",
		12 => "CURLE_FTP_WEIRD_USER_REPLY",
		13 => "CURLE_FTP_WEIRD_PASV_REPLY",
		14 => "CURLE_FTP_WEIRD_227_FORMAT",
		15 => "CURLE_FTP_CANT_GET_HOST",
		16 => "CURLE_FTP_CANT_RECONNECT",
		17 => "CURLE_FTP_COULDNT_SET_BINARY",
		18 => "CURLE_FTP_PARTIAL_FILE or CURLE_PARTIAL_FILE",
		19 => "CURLE_FTP_COULDNT_RETR_FILE",
		20 => "CURLE_FTP_WRITE_ERROR",
		21 => "CURLE_FTP_QUOTE_ERROR",
		25 => "CURLE_FTP_COULDNT_STOR_FILE",
		31 => "CURLE_FTP_COULDNT_USE_REST",
		32 => "CURLE_FTP_COULDNT_GET_SIZE",
		35 => "CURLE_SSL_CONNECT_ERROR",
		36 => "CURLE_BAD_DOWNLOAD_RESUME or CURLE_FTP_BAD_DOWNLOAD_RESUME",
		37 => "CURLE_FILE_COULDNT_READ_FILE",
		63 => "CURLE_FILESIZE_EXCEEDED",
		64 => "CURLE_FTP_SSL_FAILED"
);
?>